name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  anchor_scroll_controller: ^0.4.4
  flutter:
    sdk: flutter
  firebase_core: any
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  fl_chart: ^0.64.0
  google_sign_in: ^6.1.6
  flutter_svg: ^2.0.9
  form_field_validator: ^1.1.0
  dotted_border: ^2.1.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/profile_default0.png
    - lib/assets/images/profile_default1.png
    - lib/assets/images/google_icon.png
    - lib/assets/images/ryan_gosling.jpg
  fonts:
    - family: SovMod
      fonts:
        - asset: lib/assets/fonts/SovMod.ttf
    - family: ViaodaLibre-Regular
      fonts:
        - asset: lib/assets/fonts/ViaodaLibre-Regular.ttf
    - family: Inter-Regular
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: lib/assets/fonts/Inter-Medium.ttf
    - family: Inter-Thin
      fonts:
        - asset: lib/assets/fonts/Inter-Thin.ttf
